### ISSUE TITLE
Docker Volume Issue

### ISSUE THREAD

**Issue by endeffects** [loic-sharma/BaGet#363]
I try to use BaGet as local nuget source, so i wrote the following docker compose file. The baget service runs as expected, but when i delete the container, the network, the volume and after all the image and start over for a clean baget instance i see all previous uploaded and mirrored packages. Which is bad by design and bad to start from the scratch. Btw: I also deleted the offline package store for my local user before.

```
version: '3.7'

volumes:
  baget-data:
      name: baget-data

networks:
  internal-net:
    name: internal-net
    driver: bridge

services:
  baget:
    image: loicsharma/baget:latest
    container_name: baget
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Storage__Type=FileSystem
      - Storage__Path=/var/baget/packages
      - Database__Type=Sqlite
      - Database__ConnectionString=Data Source=/var/baget/baget.db
      - Search__Type=Database
      - ApiKey=MySecretApi
      - AllowPackageOverwrites=true
      - PackageDeletionBehavior=HardDelete
      - Mirror__Enabled=true
    volumes:
      - baget-data:/var/baget
    ports:
      - 5555:80
    networks: 
      - internal-net

```
