### ISSUE TITLE
Multiple (nested) 'packages' directories under my volume

### ISSUE THREAD

**Issue by rong0312** [loic-sharma/BaGet#440]
### Describe the bug
The solution creates nested 'packages' directory

### To Reproduce
Looking at my volume

### Expected behavior
Only one 'packages' directory with all my private packages & cached packages.

### Screenshots
Please notice the path:

![Screen Shot 2020-01-14 at 14 37 03](https://user-images.githubusercontent.com/33253167/72345467-8a58c580-36dc-11ea-9c03-680426dc9bb8.png)

### Additional context
Most of the nested directories contain the same packages and versions, however, there are some differentials between directories "depth" (both packages & versions);

![Screen Shot 2020-01-14 at 14 48 17](https://user-images.githubusercontent.com/33253167/72345644-f5a29780-36dc-11ea-88ca-ae2f5873e311.png)

This is my nuget's compose;

```
nuget:
    image: loicsharma/baget
    container_name: "nuget"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ApiKeyHash=E1E61EE36C7C76DB28D43C13BEDAB5701F9C693009491D672981B3435AF51D3F
      - Storage__Type=FileSystem
      - Storage__Path=/var/baget/packages
      - PackageDeletionBehavior=HardDelete
      - Database__Type=Sqlite
      - Database__ConnectionString=Data Source=/var/baget/baget.db
      - Search__Type=Database
    volumes:
      - ./nuget:/var/baget
    restart: unless-stopped
.
.
.
```

Any suggestions?
