### ISSUE TITLE
Timeouts when using NFS as storage in kubernetes

### ISSUE THREAD

**Issue by gzres** [loic-sharma/BaGet#512]
### Describe the bug
I get timeouts during push or download packages when using NFS as storage in kubernetes cluster.

### To Reproduce
1. Using this version of BaGet: latest from dockerhub (loicsharma/baget:636c38146791bf7bdaa297587e196508f732cd08)
Kubernetes: v1.16.2
2. Deploy in kubernetes cluster via yml:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: utils
---
apiVersion: v1
kind: Service
metadata:
  namespace: utils
  name: baget
spec:
  ports:
    - name: http
      port: 80
      nodePort: 31125
  type: "NodePort"
  selector:
    product: utils
    service: baget
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: utils
  name: baget
spec:
  selector:
    matchLabels:
      product: utils
      service: baget
  replicas: 1
  template:
    metadata:
      labels:
        product: utils
        service: baget
    spec:
      containers:
        - name: baget
          image: loicsharma/baget:636c38146791bf7bdaa297587e196508f732cd08
          imagePullPolicy: Always
          volumeMounts:
            - name: nfs-volume
              mountPath: /app/packages
          env:
            - name: Storage__Path
              value: '/app/packages'
            - name: Database__Type
              value: SqlServer
            - name: Database__ConnectionString
              value: "Server=<SERVER_IP>;Database=nuget;User Id=<USER>;Password=<PASS>"
            - name: ApiKey
              value: API_KEY
      volumes:
        - name: nfs-volume
          nfs:
            server: <NFS_IP>
            path: /files/nfs4/nuget
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
```

3. Deploy nginx proxy for kubernetes:
```
server {
    server_name nuget;
    listen              <Nginx_IP>:443 ssl;
    ssl_certificate     /xxx/crt/bundle.pem;
    ssl_certificate_key /xxx/privateKey.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    access_log   /var/log/nginx/nuget.access.log;
    error_log    /var/log/nginx/nuget.error.log;

    location / {
        proxy_pass http://kubernetes:31125;
        proxy_http_version      1.1;
        proxy_cache_bypass      $http_upgrade;
        proxy_set_header        Upgrade                 $http_upgrade;
        proxy_set_header        Connection              keep-alive;
        proxy_set_header        Host                    $host;
        proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto       $scheme;
        proxy_set_header        X-Forwarded-Host        $host:$server_port;
        proxy_set_header        X-Forwarded-Port        $server_port;
        proxy_set_header        X-Real-IP               $remote_addr;
    }
}
```

### Expected behavior
Packages should push and download without errors.
### Additional context
Log from nginx:
```
2020/05/08 11:10:18 [error] 29591#0: *9098 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.8.0.18, server: nuget, request: "GET /v3/package/xxx/1.0.0/xxx.1.0.0.nupkg HTTP/1.1", upstream: "http://<Kubernetes_IP>:31125/v3/package/xxx/1.0.0/xxx.1.0.0.nupkg", host: "nuget", referrer: "https://nuget/packages/xxx"
```

I'm able to crate and read files in /app/packages from shell in kubernetes pod.
When I deployed BaGet without nfs mount everything works fine.

Any idea how to solve this problem?
Thanks

Edit:
I also checked configure NFS via PVC.
Same situation.
BaGet create dictionaries, .nupkg file (file is empty) and no entries in db.
