### ISSUE TITLE
Nginx path is ignored? Bug or wrong configuration?

### ISSUE THREAD

**Issue by goors** [loic-sharma/BaGet#735]
I have Kubernetes with ingress config:

`path: /nuget(/|$)(.*)`

I thought that using PathBase as env variable with resolve issue, but it is not.

In this case I thought setting PathBase=/nuget with resolve this but when I got to mydomain.com/nuget/v3/index.json
In response JSON, I have mydomain.com/api/v2/package in  instead of mydomain.com/nuget/api/v2/package.

What am I missing here?

**Comment by Rayvor** [comment]
I think you have a config like this

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-test
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
   - host: test.domain.com
     http:
       paths:
       - path: /nuget(/|$)(.*)  # test.domain.com/nuget would redirect to the baget-service:80/
         pathType: Prefix
         backend:
           service:
             name: baget-service
             port:
               number: 80
```

you should change to something like this
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-test
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$3
spec:
  rules:
   - host: test.domain.com
     http:
       paths:
       - path: /(nuget)(/|$)(.*)  # test.domain.com/nuget would redirect to the baget-service:80/nuget
         pathType: Prefix
         backend:
           service:
             name: baget-service
             port:
               number: 80
```
